// cronman — Author: Konstantinos Patronas <kpatronas@gmail.com>

package main

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// LineKind classifies a single crontab line.
type LineKind int

const (
	KBlank   LineKind = iota
	KComment          // a real comment (prose, headers, examples)
	KEnv              // NAME=value
	KJob              // a job, active or commented out (Disabled)
	KInvalid          // non-comment line that cron cannot parse
)

// Line is one line of a crontab. Unmodified lines render back byte-for-byte.
type Line struct {
	Num      int
	Raw      string
	Kind     LineKind
	Disabled bool   // job that is commented out
	Prefix   string // original comment prefix of a disabled job, e.g. "## "
	Body     string // job text without the comment prefix
	Schedule string // "*/5 * * * *" or "@daily"
	User     string // system crontabs (/etc/crontab, /etc/cron.d) only
	Command  string
	EnvName  string
	EnvValue string
	Err      string
	Modified bool

	origDisabled bool
	origPrefix   string
}

// Crontab is a parsed crontab file.
type Crontab struct {
	Lines  []*Line
	System bool // has a user field (/etc/crontab, /etc/cron.d/*)
}

var specialSchedules = map[string]string{
	"@reboot":   "",
	"@yearly":   "0 0 1 1 *",
	"@annually": "0 0 1 1 *",
	"@monthly":  "0 0 1 * *",
	"@weekly":   "0 0 * * 0",
	"@daily":    "0 0 * * *",
	"@midnight": "0 0 * * *",
	"@hourly":   "0 * * * *",
}

var (
	envRe  = regexp.MustCompile(`^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$`)
	userRe = regexp.MustCompile(`^[A-Za-z0-9._][A-Za-z0-9._-]*\$?$`)
	wsRe   = regexp.MustCompile(`[ \t]+`)
)

// Template text shipped in distro crontab headers. These look like jobs once the
// '#' is stripped but are documentation, never something to enable.
var exampleCommands = []string{
	"command to be executed",
	"user-name command to be executed",
	"tar -zcf /var/backups/home.tgz /home/",
}

var headerMarkers = []string{
	"Edit this file to introduce tasks to be run by cron",
	"Example of job definition",
	"DO NOT EDIT THIS FILE",
}

// ParseCrontab parses crontab text. system=true expects a user field after the schedule.
func ParseCrontab(content string, system bool) *Crontab {
	c := &Crontab{System: system}
	content = strings.TrimSuffix(content, "\n")
	if content == "" {
		return c
	}
	raws := strings.Split(content, "\n")
	headerEnd := headerBlockEnd(raws)
	for i, raw := range raws {
		l := parseLine(raw, system)
		l.Num = i + 1
		if i < headerEnd && l.Kind == KJob && l.Disabled {
			l = &Line{Num: i + 1, Raw: raw, Kind: KComment}
		}
		c.Lines = append(c.Lines, l)
	}
	return c
}

// headerBlockEnd returns the number of leading comment lines that form a distro
// template header (0 if the leading comments are not such a header).
func headerBlockEnd(raws []string) int {
	end := 0
	isHeader := false
	for end < len(raws) {
		t := strings.TrimSpace(raws[end])
		if t != "" && !strings.HasPrefix(t, "#") {
			break
		}
		for _, m := range headerMarkers {
			if strings.Contains(t, m) {
				isHeader = true
			}
		}
		end++
	}
	if !isHeader {
		return 0
	}
	return end
}

func parseLine(raw string, system bool) *Line {
	l := &Line{Raw: raw}
	t := strings.TrimLeft(raw, " \t")
	switch {
	case strings.TrimSpace(t) == "":
		l.Kind = KBlank
	case strings.HasPrefix(t, "#"):
		l.Kind = KComment
		rest := strings.TrimLeft(t, "#")
		rest = strings.TrimLeft(rest, " \t")
		if rest == "" {
			return l
		}
		sched, user, cmd, err := parseJobText(rest, system)
		if err != nil || isExampleCommand(cmd, user) {
			return l
		}
		l.Kind = KJob
		l.Disabled, l.origDisabled = true, true
		l.Prefix = raw[:len(raw)-len(rest)]
		l.origPrefix = l.Prefix
		l.Body = rest
		l.Schedule, l.User, l.Command = sched, user, cmd
	case envRe.MatchString(t) && !looksLikeSchedule(t):
		m := envRe.FindStringSubmatch(t)
		l.Kind = KEnv
		l.EnvName, l.EnvValue = m[1], unquoteEnv(strings.TrimRight(m[2], " \t"))
	default:
		sched, user, cmd, err := parseJobText(t, system)
		if err != nil {
			l.Kind = KInvalid
			l.Err = err.Error()
			return l
		}
		l.Kind = KJob
		l.Body = t
		l.Schedule, l.User, l.Command = sched, user, cmd
	}
	return l
}

func looksLikeSchedule(s string) bool {
	_, _, _, err := parseJobText(s, false)
	return err == nil
}

func isExampleCommand(cmd, user string) bool {
	full := strings.TrimSpace(cmd)
	if user != "" {
		full = user + " " + full
	}
	for _, e := range exampleCommands {
		if strings.TrimSpace(cmd) == e || full == e {
			return true
		}
	}
	return false
}

func unquoteEnv(v string) string {
	if len(v) >= 2 && (v[0] == '"' || v[0] == '\'') && v[len(v)-1] == v[0] {
		return v[1 : len(v)-1]
	}
	return v
}

// splitFields splits off n whitespace-separated fields and returns them plus the
// untouched remainder.
func splitFields(s string, n int) ([]string, string, bool) {
	var fields []string
	rest := strings.TrimLeft(s, " \t")
	for len(fields) < n {
		if rest == "" {
			return nil, "", false
		}
		i := strings.IndexAny(rest, " \t")
		if i < 0 {
			fields = append(fields, rest)
			rest = ""
			continue
		}
		fields = append(fields, rest[:i])
		rest = strings.TrimLeft(rest[i:], " \t")
	}
	return fields, rest, true
}

// parseJobText parses "<schedule> [user] <command>".
func parseJobText(s string, system bool) (sched, user, cmd string, err error) {
	s = strings.TrimLeft(s, " \t")
	nSched := 5
	if strings.HasPrefix(s, "@") {
		nSched = 1
	}
	n := nSched
	if system {
		n++
	}
	fields, rest, ok := splitFields(s, n)
	if !ok || strings.TrimSpace(rest) == "" {
		return "", "", "", fmt.Errorf("missing command")
	}
	sched = strings.Join(fields[:nSched], " ")
	if err := ValidateSchedule(sched); err != nil {
		return "", "", "", err
	}
	if system {
		user = fields[nSched]
		if !userRe.MatchString(user) {
			return "", "", "", fmt.Errorf("invalid user field %q", user)
		}
	}
	return sched, user, rest, nil
}

type fieldSpec struct {
	name     string
	min, max int
	names    []string
}

var fieldSpecs = []fieldSpec{
	{"minute", 0, 59, nil},
	{"hour", 0, 23, nil},
	{"day of month", 1, 31, nil},
	{"month", 1, 12, []string{"", "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"}},
	{"day of week", 0, 7, []string{"sun", "mon", "tue", "wed", "thu", "fri", "sat"}},
}

// ValidateSchedule checks a 5-field schedule or an @keyword.
func ValidateSchedule(sched string) error {
	sched = strings.TrimSpace(sched)
	if strings.HasPrefix(sched, "@") {
		if _, ok := specialSchedules[strings.ToLower(sched)]; !ok {
			return fmt.Errorf("unknown special schedule %q", sched)
		}
		return nil
	}
	f := wsRe.Split(sched, -1)
	if len(f) != 5 {
		return fmt.Errorf("need 5 fields (minute hour day-of-month month day-of-week), got %d", len(f))
	}
	for i, fv := range f {
		if _, err := expandField(i, fv); err != nil {
			return err
		}
	}
	return nil
}

func parseFieldValue(spec fieldSpec, s string) (int, error) {
	if n, err := strconv.Atoi(s); err == nil {
		if n < spec.min || n > spec.max {
			return 0, fmt.Errorf("%s value %d out of range %d-%d", spec.name, n, spec.min, spec.max)
		}
		return n, nil
	}
	for i, nm := range spec.names {
		if nm != "" && strings.EqualFold(s, nm) {
			return i, nil
		}
	}
	return 0, fmt.Errorf("invalid %s value %q", spec.name, s)
}

// expandField returns the set of values matched by field i.
func expandField(i int, f string) ([]bool, error) {
	spec := fieldSpecs[i]
	set := make([]bool, spec.max+1)
	if f == "" {
		return nil, fmt.Errorf("empty %s field", spec.name)
	}
	for _, item := range strings.Split(f, ",") {
		if item == "" {
			return nil, fmt.Errorf("empty item in %s field %q", spec.name, f)
		}
		rng, step := item, 1
		if j := strings.Index(item, "/"); j >= 0 {
			rng = item[:j]
			s, err := strconv.Atoi(item[j+1:])
			if err != nil || s < 1 {
				return nil, fmt.Errorf("invalid step in %s field %q", spec.name, item)
			}
			step = s
		}
		lo, hi := spec.min, spec.max
		switch {
		case rng == "*":
		case strings.Contains(rng, "-"):
			parts := strings.SplitN(rng, "-", 2)
			a, err := parseFieldValue(spec, parts[0])
			if err != nil {
				return nil, err
			}
			b, err := parseFieldValue(spec, parts[1])
			if err != nil {
				return nil, err
			}
			if a > b {
				return nil, fmt.Errorf("invalid range %q in %s field", rng, spec.name)
			}
			lo, hi = a, b
		default:
			a, err := parseFieldValue(spec, rng)
			if err != nil {
				return nil, err
			}
			lo = a
			if step == 1 {
				hi = a
			}
		}
		for v := lo; v <= hi; v += step {
			set[v] = true
		}
	}
	if i == 4 && set[7] {
		set[0] = true
	}
	return set, nil
}

// Jobs returns all active and disabled jobs.
func (c *Crontab) Jobs() []*Line {
	var out []*Line
	for _, l := range c.Lines {
		if l.Kind == KJob {
			out = append(out, l)
		}
	}
	return out
}

// EnvAt returns the environment cron gives a job at line index idx
// (assignments above it, on top of cron's defaults).
func (c *Crontab) EnvAt(l *Line, home string) map[string]string {
	env := map[string]string{"PATH": "/usr/bin:/bin", "SHELL": "/bin/sh"}
	if home != "" {
		env["HOME"] = home
	}
	for _, x := range c.Lines {
		if x == l {
			break
		}
		if x.Kind == KEnv {
			env[x.EnvName] = x.EnvValue
		}
	}
	return env
}

// SetDisabled comments a job out or back in.
func (l *Line) SetDisabled(d bool) {
	if l.Disabled == d {
		return
	}
	l.Disabled = d
	if d {
		l.Prefix = l.origPrefix
		if l.Prefix == "" {
			l.Prefix = "# "
		}
	}
	l.Modified = true
}

// SetSchedule replaces the schedule, keeping the command.
func (l *Line) SetSchedule(s string) error {
	s = strings.Join(wsRe.Split(strings.TrimSpace(s), -1), " ")
	if err := ValidateSchedule(s); err != nil {
		return err
	}
	l.Schedule = s
	l.rebuild()
	return nil
}

// SetCommand replaces the command, keeping the schedule.
func (l *Line) SetCommand(cmd string) error {
	cmd = strings.TrimSpace(cmd)
	if cmd == "" {
		return fmt.Errorf("command cannot be empty")
	}
	if strings.Contains(cmd, "\n") {
		return fmt.Errorf("command cannot contain newlines")
	}
	l.Command = cmd
	l.rebuild()
	return nil
}

func (l *Line) rebuild() {
	parts := []string{l.Schedule}
	if l.User != "" {
		parts = append(parts, l.User)
	}
	parts = append(parts, l.Command)
	l.Body = strings.Join(parts, " ")
	l.Modified = true
}

// Render returns the text of the line as it should be written.
func (l *Line) Render() string {
	if !l.Modified {
		return l.Raw
	}
	if l.Disabled {
		return l.Prefix + l.Body
	}
	return l.Body
}

// Render returns the whole crontab, always newline-terminated (cron requires it).
func (c *Crontab) Render() string {
	var b strings.Builder
	for _, l := range c.Lines {
		b.WriteString(l.Render())
		b.WriteByte('\n')
	}
	return b.String()
}

// CronShellPart returns the part of a cron command that goes to the shell:
// everything before the first unescaped '%' (the rest becomes stdin).
func CronShellPart(cmd string) string {
	var b strings.Builder
	for i := 0; i < len(cmd); i++ {
		c := cmd[i]
		if c == '\\' && i+1 < len(cmd) && cmd[i+1] == '%' {
			b.WriteByte('%')
			i++
			continue
		}
		if c == '%' {
			break
		}
		b.WriteByte(c)
	}
	return b.String()
}
